apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2021-11-24T14:37:58Z"
  generation: 2
  labels:
    app: my-app-js
  name: my-app-js
  namespace: default
  resourceVersion: "2515"
  uid: ddb8aa1a-dfe9-4083-8e48-2e2df1b28ac6
spec:
  progressDeadlineSeconds: 600
  replicas: 5
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: my-app-js
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-app-js
    spec:
      containers:
      - image: tsaussac/node-app
        imagePullPolicy: Always
        name: node-app
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 5
  conditions:
  - lastTransitionTime: "2021-11-24T14:51:43Z"
    lastUpdateTime: "2021-11-24T14:51:43Z"
    message: ReplicaSet "my-app-js-b8cb95594" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2021-11-24T15:09:07Z"
    lastUpdateTime: "2021-11-24T15:09:07Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 2
  readyReplicas: 5
  replicas: 5
  updatedReplicas: 5
